# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
