# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review_text',
        ),
    ]
